import type { Task } from "@/components/TaskCard";

// No seed tasks — tasks will be posted by real recruiters
export const tasks: Task[] = [];

// No seed notifications — notifications will be generated by real platform activity
export const notifications: never[] = [];
