import type { Task } from "@/components/TaskCard";

export const tasks: Task[] = [
  {
    id: "design-landing",
    title: "Design a landing page for an AI note-taking app",
    recruiter: "Priya Sharma · Design Lead",
    company: "Notion-style Co.",
    logo: "N",
    skills: ["Figma", "UI Design", "Prototyping"],
    difficulty: "Intermediate",
    deadline: "3d left",
    time: "~4 hrs",
    accent: "linear-gradient(135deg,#6366F1,#8B5CF6)",
  },
  {
    id: "react-dashboard",
    title: "Build a React dashboard for tracking SaaS metrics",
    recruiter: "Arjun Mehta · Engineering Manager",
    company: "Stripeful",
    logo: "S",
    skills: ["React", "TypeScript", "Charts"],
    difficulty: "Advanced",
    deadline: "5d left",
    time: "~8 hrs",
    accent: "linear-gradient(135deg,#2563EB,#22C55E)",
  },
  {
    id: "copy-onboarding",
    title: "Write onboarding copy for a fintech mobile app",
    recruiter: "Sara Williams · Brand Lead",
    company: "Lumen Pay",
    logo: "L",
    skills: ["Copywriting", "UX Writing"],
    difficulty: "Beginner",
    deadline: "2d left",
    time: "~2 hrs",
    accent: "linear-gradient(135deg,#22C55E,#2563EB)",
  },
  {
    id: "data-analysis",
    title: "Analyze user churn from a CSV and present insights",
    recruiter: "Rohit K. · Data Scientist",
    company: "Cohorted",
    logo: "C",
    skills: ["Python", "Pandas", "Storytelling"],
    difficulty: "Intermediate",
    deadline: "4d left",
    time: "~5 hrs",
    accent: "linear-gradient(135deg,#0F172A,#6366F1)",
  },
  {
    id: "brand-mark",
    title: "Create a brand mark and color system for a campus club",
    recruiter: "Ananya R. · Founder",
    company: "Build Club",
    logo: "B",
    skills: ["Branding", "Illustrator"],
    difficulty: "Beginner",
    deadline: "6d left",
    time: "~3 hrs",
    accent: "linear-gradient(135deg,#F59E0B,#EF4444)",
  },
];

export const notifications = [
  {
    id: "1",
    type: "task" as const,
    title: "New task matches your skills",
    body: "Design Lead at Notion-style Co. posted a UI challenge.",
    time: "2m ago",
    unread: true,
  },
  {
    id: "2",
    type: "view" as const,
    title: "A recruiter viewed your profile",
    body: "Stripeful · Engineering Manager",
    time: "1h ago",
    unread: true,
  },
  {
    id: "3",
    type: "status" as const,
    title: "Your submission is being reviewed",
    body: "“Landing page for AI notes” — Notion-style Co.",
    time: "Yesterday",
    unread: false,
  },
  {
    id: "4",
    type: "badge" as const,
    title: "Achievement unlocked: 🔥 First Five",
    body: "You completed 5 tasks. Keep the streak going!",
    time: "2d ago",
    unread: false,
  },
];
